package schema

import (
	"fmt"
	"sort"
	"strings"
)

type PrologWriter struct{}

func NewPrologWriter() *PrologWriter {
	return &PrologWriter{}
}

// Write vygeneruje Prolog fakta popisující schéma. Fakta jsou seskupená podle
// predikátu (všechny field/2, pak všechny field_type/3, …), aby soubor šel
// načíst i do striktních ISO interpretů, které odmítají nesouvislé
// (discontiguous) definice predikátů.
func (w *PrologWriter) Write(s *IndexSchema) string {
	fields := make([]Field, len(s.Fields))
	copy(fields, s.Fields)
	sort.SliceStable(fields, func(i, j int) bool {
		return fields[i].Path < fields[j].Path
	})

	idx := atom(s.Name)
	groups := []struct {
		name string
		emit func(f Field) (string, bool)
	}{
		{"field/2", func(f Field) (string, bool) {
			return fmt.Sprintf("field(%s, %s).", idx, atom(f.Path)), true
		}},
		{"field_type/3", func(f Field) (string, bool) {
			return fmt.Sprintf("field_type(%s, %s, %s).", idx, atom(f.Path), atom(f.Type)), f.Type != ""
		}},
		{"object/2", func(f Field) (string, bool) {
			return fmt.Sprintf("object(%s, %s).", idx, atom(f.Path)), f.IsObject
		}},
		{"nested/2", func(f Field) (string, bool) {
			return fmt.Sprintf("nested(%s, %s).", idx, atom(f.Path)), f.IsNested
		}},
		{"analyzer/3", func(f Field) (string, bool) {
			return fmt.Sprintf("analyzer(%s, %s, %s).", idx, atom(f.Path), atom(f.Analyzer)), f.Analyzer != ""
		}},
		{"format/3", func(f Field) (string, bool) {
			return fmt.Sprintf("format(%s, %s, %s).", idx, atom(f.Path), atom(f.Format)), f.Format != ""
		}},
		{"ignore_above/3", func(f Field) (string, bool) {
			if f.IgnoreAbove == nil {
				return "", false
			}
			return fmt.Sprintf("ignore_above(%s, %s, %d).", idx, atom(f.Path), *f.IgnoreAbove), true
		}},
		{"indexed/3", func(f Field) (string, bool) {
			if f.Indexed == nil {
				return "", false
			}
			return fmt.Sprintf("indexed(%s, %s, %t).", idx, atom(f.Path), *f.Indexed), true
		}},
		{"doc_values/3", func(f Field) (string, bool) {
			if f.DocValues == nil {
				return "", false
			}
			return fmt.Sprintf("doc_values(%s, %s, %t).", idx, atom(f.Path), *f.DocValues), true
		}},
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("%% Generated by schema-export for index %s. Do not edit by hand.\n", s.Name))
	b.WriteString(fmt.Sprintf("index(%s).\n", idx))
	for _, g := range groups {
		var lines []string
		for _, f := range fields {
			if line, ok := g.emit(f); ok {
				lines = append(lines, line)
			}
		}
		if len(lines) == 0 {
			continue
		}
		b.WriteString("\n% " + g.name + "\n")
		b.WriteString(strings.Join(lines, "\n"))
		b.WriteString("\n")
	}
	return b.String()
}

// atom vrátí Prolog atom — bez uvozovek jen tehdy, když je to platný
// "letter-digit" atom (začíná malým písmenem, dál písmena, číslice, _).
// Tečka v holém atomu platná není (např. http.status), takové názvy se
// quotují; apostrofy a zpětná lomítka se escapují.
func atom(s string) string {
	if s == "" {
		return "''"
	}
	ok := true
	for i, r := range s {
		if i == 0 {
			if !(r >= 'a' && r <= 'z') {
				ok = false
				break
			}
		} else if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_') {
			ok = false
			break
		}
	}
	if ok {
		return s
	}
	esc := strings.ReplaceAll(s, `\`, `\\`)
	esc = strings.ReplaceAll(esc, "'", `\'`)
	return "'" + esc + "'"
}
